//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class EmployeeMetadata
    {
        [Required]
        public int Id { get; set; }
        [Required]
        public string FullName { get; set; }
        [Required]
        public string Gender { get; set; }
        
        public int Age { get; set; }
        
        public DateTime HireDate { get; set; }
        [Required]
        public string EmailAddress { get; set; }
       
        public  int Salary { get; set; }
        [Required]
        public string PersonalWebSite { get; set; }
        [Required]
        public string Photo { get; set; }
        
        public string AlternateText { get; set; }
    }
}

    [MetadataType(typeof(EmployeeMetadata))]
    public partial class DemotblEmployee
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> Salary { get; set; }
        public string PersonalWebSite { get; set; }
        public string Photo { get; set; }
        public string AlternateText { get; set; }
    }
}
